import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="flex flex-row justify-between items-center px-4 h-16 border-b border-gray-200">
          {/* logo */}
          <Link href="/">
            <h1 className="text-xl py-1 px-2 font-bold">My Secret Blog</h1>
          </Link>
          <nav>
            <Link href="/" className="p-2">
              Home
            </Link>
            <Link href="/about" className="p-2">
              About
            </Link>
            <Link href="/contact" className="p-2">
              Contact
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
